import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_REPO_ROOT, loadReviews } from "./reviews";
import type { ReviewImage, ReviewIssue } from "../src/content/review-types";

const SITE_URL = "https://risksinsync.com";
const FALLBACK_IMAGE = "/risksinsync-og.png";
const FALLBACK_ALT = "Risks In Sync";

function html(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function publicImagePath(review: ReviewIssue, image: ReviewImage): string {
  return `/review/${review.slug}/${image.path}`;
}

function issueHtml(review: ReviewIssue): string {
  const social = review.images.find((image) => image.role === "social")
    ?? review.images.find((image) => image.role === "hero")
    ?? review.images.find((image) => image.role === "homepage");
  const imagePath = social ? publicImagePath(review, social) : FALLBACK_IMAGE;
  const imageAlt = social ? social.alt : FALLBACK_ALT;
  const canonical = `${SITE_URL}${review.path}`;
  const imageUrl = `${SITE_URL}${imagePath}`;
  const pageTitle = `${review.title} | Cascade Risk Review`;
  const formName = `private-feedback-${review.slug}`;

  return `<!doctype html>
<!-- GENERATED by npm run generate:reviews. Do not edit. -->
<html lang="${html(review.language)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#22211f" />
    <meta name="application-name" content="Risks In Sync" />
    <meta name="apple-mobile-web-app-title" content="Risks In Sync" />
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="icon" href="/favicon-32x32.png" type="image/png" sizes="32x32" />
    <link rel="icon" href="/favicon-16x16.png" type="image/png" sizes="16x16" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180" />
    <link rel="manifest" href="/site.webmanifest" />
    <link rel="canonical" href="${html(canonical)}" />
    <meta name="description" content="${html(review.summary)}" />
    <meta property="og:title" content="${html(pageTitle)}" />
    <meta property="og:description" content="${html(review.summary)}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="${html(canonical)}" />
    <meta property="og:site_name" content="Risks In Sync" />
    <meta property="og:image" content="${html(imageUrl)}" />
    <meta property="og:image:alt" content="${html(imageAlt)}" />
    <meta property="article:published_time" content="${html(review.publication_date)}" />
    <meta property="article:author" content="${html(review.author)}" />
    <meta name="author" content="${html(review.author)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${html(pageTitle)}" />
    <meta name="twitter:description" content="${html(review.summary)}" />
    <meta name="twitter:image" content="${html(imageUrl)}" />
    <meta name="twitter:image:alt" content="${html(imageAlt)}" />
    <title>${html(pageTitle)}</title>
  </head>
  <body>
    <div id="root"></div>
    <form name="${html(formName)}" method="post" data-netlify="true" netlify-honeypot="bot-field" hidden>
      <input type="hidden" name="form-name" value="${html(formName)}" />
      <input type="hidden" name="issue" value="${html(review.slug)}" />
      <input name="bot-field" />
      <input type="radio" name="answer" value="yes_clearly" required />
      <input type="radio" name="answer" value="not_really" />
      <input type="radio" name="answer" value="hard_to_tell" />
      <textarea name="comment" maxlength="400"></textarea>
    </form>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

export function generateReviews(repoRoot = DEFAULT_REPO_ROOT): { count: number; slugs: string[] } {
  const { published } = loadReviews(repoRoot);
  if (!published.length) throw new Error("No ready_for_pr reviews were found; refusing to generate an empty publication");

  const generatedSource = join(repoRoot, "src", "generated");
  mkdirSync(generatedSource, { recursive: true });
  const reviews = published.map(({ review }) => review);
  writeFileSync(
    join(generatedSource, "reviews.ts"),
    `// GENERATED by npm run generate:reviews. Do not edit.\nimport type { ReviewIssue } from "../content/review-types";\n\nexport const reviews: ReviewIssue[] = ${JSON.stringify(reviews, null, 2)};\n`,
  );

  const entries: Record<string, string> = {};
  for (const review of reviews) {
    const issueDirectory = join(repoRoot, "review", review.slug);
    mkdirSync(issueDirectory, { recursive: true });
    const entry = join(issueDirectory, "index.html");
    writeFileSync(entry, issueHtml(review));
    entries[`review-${review.slug}`] = relative(repoRoot, entry);
  }
  writeFileSync(
    join(repoRoot, "review", ".generated-entries.json"),
    `${JSON.stringify(entries, null, 2)}\n`,
  );
  return { count: reviews.length, slugs: reviews.map((review) => review.slug) };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  try {
    const result = generateReviews();
    console.log(`Generated ${result.count} review${result.count === 1 ? "" : "s"}: ${result.slugs.join(", ")}`);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
